monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.pci-0000_03_00.1.pro-output-7" }
      { node.name = "alsa_output.pci-0000_03_00.1.pro-output-8" }
      { node.name = "alsa_output.pci-0000_03_00.1.pro-output-9" }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_output.pci-0000_03_00.1.pro-output-3" }
    ]
    actions = {
      update-props = {
        node.description = "Audioengine A2+ (HDMI)"
        node.nick = "Audioengine A2+ (HDMI)"
      }
    }
  }
]
