#!/usr/bin/env sh

#sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

yabai -m config external_bar all:35:0 \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_zoom_persist off \
	window_placement second_child \
	window_topmost off \
	window_shadow float \
	window_opacity on \
	window_opacity_duration 0.2 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.95 \
	window_animation_duration 0.3 \
	insert_feedback_color 0xff9dd274 \
	split_ratio 0.50 \
	auto_balance off \
	auto_padding on \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	top_padding 14 \
	bottom_padding 8 \
	left_padding 8 \
	right_padding 8 \
	window_gap 10
# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|System Preferences|System Settings|Archive Utility|Alfred)$" manage=off
yabai -m rule --add app="^(Docker Desktop|Parallels Desktop|Clockify|Gnucash)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="Steam"  manage=off
yabai -m rule --add app="Kerbal Space Program"  manage=off
yabai -m rule --add title="^Floating:" manage=off grid=3:3:1:1:1:1

yabai -m config layout bsp
# S K E T C H Y B A R  E V E N T S
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

echo "yabai configuration loaded.."
